### ISSUE TITLE
erreur

### ISSUE THREAD

**Issue by phid78** [gvigroux/freebox_home#5]
bonjour, j'ai ces erreurs, qui concernent ce git et l'officiel : 
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:698
First occurred: 14:08:16 (80 occurrences)
Last logged: 21:21:59

Update for switch.freebox_wifi fails
Update for cover.volet_cabinet_1 fails
Update for cover.volet_salle_d_attente fails
Update for cover.volet_cabinet_2_2 fails
Update for cover.volet_cabinet_4 fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 698, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 959, in async_device_update
    await self.async_update()
  File "/config/custom_components/freebox_home/cover.py", line 84, in async_update
    self._state = self.convert_state(await self.get_home_endpoint_value(self._command_state))
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/freebox_home/base_class.py", line 84, in get_home_endpoint_value
    node = await self._router._api.home.get_home_endpoint_value(self._id, command_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/freebox_api/api/home.py", line 107, in get_home_endpoint_value
    )[1:]
       ^^^
  File "/usr/local/lib/python3.11/site-packages/freebox_api/access.py", line 122, in get
    return await self._perform_request(self.session.get, end_url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/freebox_api/access.py", line 94, in _perform_request
    r = await verb(url, **request_params)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 601, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 960, in start
    with self._timer:
  File "/usr/local/lib/python3.11/site-packages/aiohttp/helpers.py", line 735, in __exit__
    raise asyncio.TimeoutError from None
TimeoutError

**Comment by gvigroux** [comment]
Difficile de comprendre l'erreur avec ce log. Apparement la librairie python utilisée n'arrive pas a ce connecter à la box (timeout)

**Comment by phid78** [comment]
depuis la mise a jour de home assistant, j'ai ca :
```
2024-01-09 20:38:28.170 WARNING (MainThread) [homeassistant.data_entry_flow] RESULT_TYPE_ABORT was used from freebox_home, this is a deprecated constant which will be removed in HA Core 2025.1. Use FlowResultType.ABORT instead, please create a bug report at https://github.com/gvigroux/freebox_home/issues
2024-01-09 20:38:30.023 WARNING (MainThread) [homeassistant.components.cover] DEVICE_CLASS_SHUTTER was used from freebox_home, this is a deprecated constant which will be removed in HA Core 2025.1. Use CoverDeviceClass.SHUTTER instead, please create a bug report at https://github.com/gvigroux/freebox_home/issues
2024-01-09 20:38:30.029 WARNING (MainThread) [homeassistant.components.cover] DEVICE_CLASS_SHUTTER was used from freebox_home, this is a deprecated constant which will be removed in HA Core 2025.1. Use CoverDeviceClass.SHUTTER instead, please create a bug report at https://github.com/gvigroux/freebox_home/issues
2024-01-09 20:38:30.257 WARNING (MainThread) [homeassistant.components.camera] SUPPORT_STREAM was used from freebox_home, this is a deprecated constant which will be removed in HA Core 2025.1. Use CameraEntityFeature.STREAM instead, please create a bug report at https://github.com/gvigroux/freebox_home/issues
2024-01-09 20:38:30.263 WARNING (MainThread) [homeassistant.components.camera] SUPPORT_ON_OFF was used from freebox_home, this is a deprecated constant which will be removed in HA Core 2025.1. Use CameraEntityFeature.ON_OFF instead, please create a bug report at https://github.com/gvigroux/freebox_home/issues
2024-01-09 20:38:30.271 WARNING (MainThread) [homeassistant.components.camera] SUPPORT_STREAM was used from freebox_home, this is a deprecated constant which will be removed in HA Core 2025.1. Use CameraEntityFeature.STREAM instead, please create a bug report at https://github.com/gvigroux/freebox_home/issues
2024-01-09 20:38:30.278 WARNING (MainThread) [homeassistant.components.camera] SUPPORT_ON_OFF was used from freebox_home, this is a deprecated constant which will be removed in HA Core 2025.1. Use CameraEntityFeature.ON_OFF instead, please create a bug report at https://github.com/gvigroux/freebox_home/issues
2024-01-09 20:38:30.456 WARNING (MainThread) [homeassistant.components.alarm_control_panel.const] SUPPORT_ALARM_ARM_AWAY was used from freebox_home, this is a deprecated constant which will be removed in HA Core 2025.1. Use AlarmControlPanelEntityFeature.ARM_AWAY instead, please create a bug report at https://github.com/gvigroux/freebox_home/issues
2024-01-09 20:38:30.465 WARNING (MainThread) [homeassistant.components.alarm_control_panel.const] SUPPORT_ALARM_ARM_CUSTOM_BYPASS was used from freebox_home, this is a deprecated constant which will be removed in HA Core 2025.1. Use AlarmControlPanelEntityFeature.ARM_CUSTOM_BYPASS instead, please create a bug report at https://github.com/gvigroux/freebox_home/issues
2024-01-09 20:38:30.473 WARNING (MainThread) [homeassistant.components.alarm_control_panel.const] SUPPORT_ALARM_ARM_HOME was used from freebox_home, this is a deprecated constant which will be removed in HA Core 2025.1. Use AlarmControlPanelEntityFeature.ARM_HOME instead, please create a bug report at https://github.com/gvigroux/freebox_home/issues
2024-01-09 20:38:30.480 WARNING (MainThread) [homeassistant.components.alarm_control_panel.const] SUPPORT_ALARM_ARM_NIGHT was used from freebox_home, this is a deprecated constant which will be removed in HA Core 2025.1. Use AlarmControlPanelEntityFeature.ARM_NIGHT instead, please create a bug report at https://github.com/gvigroux/freebox_home/issues
2024-01-09 20:38:30.487 WARNING (MainThread) [homeassistant.components.alarm_control_panel.const] SUPPORT_ALARM_TRIGGER was used from freebox_home, this is a deprecated constant which will be removed in HA Core 2025.1. Use AlarmControlPanelEntityFeature.TRIGGER instead, please create a bug report at https://github.com/gvigroux/freebox_home/issues
2024-01-09 20:38:30.518 WARNING (MainThread) [homeassistant.components.binary_sensor] DEVICE_CLASS_MOTION was used from freebox_home, this is a deprecated constant which will be removed in HA Core 2025.1. Use BinarySensorDeviceClass.MOTION instead, please create a bug report at https://github.com/gvigroux/freebox_home/issues
2024-01-09 20:38:30.525 WARNING (MainThread) [homeassistant.components.binary_sensor] DEVICE_CLASS_DOOR was used from freebox_home, this is a deprecated constant which will be removed in HA Core 2025.1. Use BinarySensorDeviceClass.DOOR instead, please create a bug report at https://github.com/gvigroux/freebox_home/issues
2024-01-09 20:38:30.532 WARNING (MainThread) [homeassistant.components.binary_sensor] DEVICE_CLASS_SAFETY was used from freebox_home, this is a deprecated constant which will be removed in HA Core 2025.1. Use BinarySensorDeviceClass.SAFETY instead, please create a bug report at https://github.com/gvigroux/freebox_home/issues
2024-01-09 20:38:30.539 WARNING (MainThread) [homeassistant.components.binary_sensor] DEVICE_CLASS_MOTION was used from freebox_home, this is a deprecated constant which will be removed in HA Core 2025.1. Use BinarySensorDeviceClass.MOTION instead, please create a bug report at https://github.com/gvigroux/freebox_home/issues
2024-01-09 20:38:30.547 WARNING (MainThread) [homeassistant.components.binary_sensor] DEVICE_CLASS_DOOR was used from freebox_home, this is a deprecated constant which will be removed in HA Core 2025.1. Use BinarySensorDeviceClass.DOOR instead, please create a bug report at https://github.com/gvigroux/freebox_home/issues
2024-01-09 20:38:30.554 WARNING (MainThread) [homeassistant.components.binary_sensor] DEVICE_CLASS_SAFETY was used from freebox_home, this is a deprecated constant which will be removed in HA Core 2025.1. Use BinarySensorDeviceClass.SAFETY instead, please create a bug report at https://github.com/gvigroux/freebox_home/issues
2024-01-09 20:38:30.585 WARNING (MainThread) [homeassistant.const] DEVICE_CLASS_BATTERY was used from freebox_home, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorDeviceClass.BATTERY instead, please create a bug report at https://github.com/gvigroux/freebox_home/issues
```

**Comment by gvigroux** [comment]
Done :)
