### ISSUE TITLE
Re-up from HA Log

### ISSUE THREAD

**Issue by JustKidding49** [gvigroux/freebox_home#8]
Enregistreur: homeassistant
Source: helpers/entity.py:966
S'est produit pour la première fois: 23:28:26 (6 occurrences)
Dernier enregistrement: 23:28:32

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/config/custom_components/freebox_home-main/binary_sensor.py", line 130, in async_update_pir
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1002, in async_write_ha_state
    self._async_verify_state_writable()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 966, in _async_verify_state_writable
    raise RuntimeError(f"Attribute hass is None for {self}")
RuntimeError: Attribute hass is None for <entity unknown.unknown=unknown>

**Comment by JustKidding49** [comment]
Je ne vois pas de souci particulier pour le fonctionnement de mes appareils (Alarme + Volet RTS) mais je vous remonte qd même les erreurs qui vous parleront peut être plus qu'à moi !

**Comment by JustKidding49** [comment]
Je rajoute cela : mon home assistant est toujours à la dernière version au moment où j'envoie ces rapports et je suis sur une greenbox nabu Casa pour le support.

Enregistreur: homeassistant.setup
Source: setup.py:334
S'est produit pour la première fois: 16:26:51 (1 occurrences)
Dernier enregistrement: 16:26:51

Setup failed for custom integration 'freebox_home': Unable to import component: No module named 'freebox_api.api.phone'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1027, in async_get_component
    self._component_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1007, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1067, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/freebox_home-main/__init__.py", line 12, in <module>
    from .router import FreeboxRouter
  File "/config/custom_components/freebox_home-main/router.py", line 7, in <module>
    from freebox_api import Freepybox
  File "/usr/local/lib/python3.12/site-packages/freebox_api/__init__.py", line 19, in <module>
    from freebox_api.aiofreepybox import Freepybox
  File "/usr/local/lib/python3.12/site-packages/freebox_api/aiofreepybox.py", line 27, in <module>
    from freebox_api.api.phone import Phone
ModuleNotFoundError: No module named 'freebox_api.api.phone'
